services:
  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=receta
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=receta
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ['CMD', 'pg_isready', '--username', 'receta', '-d', 'receta']
      retries: 3
      timeout: 30s

  web:
    build: ./recetashare-app
    container_name: recetashare-frontend
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: ng serve --host 0.0.0.0 --port 5173

    volumes:
      - ./recetashare-app/src:/app/src

  api:
    build: ./backend
    container_name: recetashare-backend
    ports:
      - "8000:80"
    volumes:
      - ./backend/src:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=receta
      - DB_USER=receta
      - DB_PASS=1234
      - DB_INIT=1


volumes:
  postgres_data: